In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
import numpy as np

In [ ]:
!pip install numpy

In [ ]:
np.__version__

Vctor or 1D Array

In [167]:
a = np.array ([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [168]:
a[3:]

array([4, 5, 6, 7])

In [169]:
a[-1]

7

In [170]:
a[2:-3]

array([3, 4])

In [171]:
a[-5:]

array([3, 4, 5, 6, 7])

In [175]:
a[-2:2]

array([], dtype=int64)

In [172]:
np.size(a)

7

In [174]:
np.shape(a)

(7,)

In [176]:
a[a[2]]

4

In [177]:
L = ([1,2,3,4,5,6,7])
L

[1, 2, 3, 4, 5, 6, 7]

In [178]:
L.reverse()
L

[7, 6, 5, 4, 3, 2, 1]

In [179]:
sorted(a, reverse = True)

[7, 6, 5, 4, 3, 2, 1]

In [180]:
a = a.reshape(1,7)
np.shape(a)

(1, 7)

In [181]:
a

array([[1, 2, 3, 4, 5, 6, 7]])

In [182]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [183]:
a[0,0]

1

In [184]:
L = ([[1,2,3],[4,5,6],[7,8,9]])
L

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [185]:
L[0][0]

1

In [186]:
a[1,:]

array([4, 5, 6])

In [188]:
a[:,-1]

array([3, 6, 9])

In [189]:
L[:][0]

[1, 2, 3]

In [ ]:
L[:][-1]

In [190]:
a[1,:] = 0
a

array([[1, 2, 3],
       [0, 0, 0],
       [7, 8, 9]])

In [191]:
a[:,1] = 0
a

array([[1, 0, 3],
       [0, 0, 0],
       [7, 0, 9]])

In [192]:
a[0:2,:] = 8
a

array([[8, 8, 8],
       [8, 8, 8],
       [7, 0, 9]])

In [193]:
np.size(a,1)

3

In [194]:
a.ndim

2

In [195]:
a.shape

(3, 3)

In [196]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

array([['one', '2'],
       ['three', '4'],
       ['five', '6']], dtype='<U5')

In [197]:
a = np.array(np_mix_matrix[:,1], dtype = int)
a

array([2, 4, 6])

In [198]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [199]:
b = np.ones((2,2))
b

array([[1., 1.],
       [1., 1.]])

In [200]:
c = np.full((5,5),8)
c

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [201]:
d = np.eye(5,5)
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [202]:
np.matmul(c,d)

array([[8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.]])

In [203]:
np.sqrt(9)

3.0

In [204]:
np.power(c,2)

array([[64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64]])

In [205]:
def addone(a):
    return a + 1

In [206]:
addone(3)

4

สุ่มในช่วง0-1

In [207]:
np.random.rand()

0.8680509159659181

In [208]:
np.round(np.random.rand()*10)

4.0

In [209]:
[np.round(np.random.rand()*10) for item in range(10)]

[4.0, 8.0, 6.0, 5.0, 9.0, 4.0, 4.0, 9.0, 5.0, 4.0]

In [210]:
np.random.randint(5)

1

In [211]:
[np.random.randint(5) for item in range(10)]

[2, 2, 3, 4, 4, 2, 0, 2, 0, 0]

In [212]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5, replace = False)

array([4, 8, 1, 2, 9])

In [213]:
np_matrix = np.round(np.random.rand(5,5))
np_matrix

array([[0., 0., 0., 0., 1.],
       [1., 1., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [214]:
idx_choose = np.random.choice(5,3, replace = False)
idx_choose

array([2, 1, 4])

In [215]:
np_matrix_choose = np_matrix[idx_choose,:]
np_matrix_choose

array([[1., 0., 0., 0., 1.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

***Ex2*****

In [216]:
B = np.random.rand(10,5)
B[:,4] = np.round(B[:,4])
B

array([[0.33525133, 0.77925449, 0.14713691, 0.75246477, 1.        ],
       [0.78972155, 0.64982762, 0.47665437, 0.56495025, 1.        ],
       [0.20719216, 0.11829315, 0.13294097, 0.24181583, 1.        ],
       [0.41736526, 0.58769839, 0.878739  , 0.10325975, 1.        ],
       [0.6028551 , 0.88803805, 0.94686981, 0.1486029 , 1.        ],
       [0.44587195, 0.08188195, 0.41478959, 0.94145777, 0.        ],
       [0.81181957, 0.23155566, 0.24337909, 0.59709022, 1.        ],
       [0.8348714 , 0.11593043, 0.15474051, 0.55191848, 1.        ],
       [0.53095884, 0.45031284, 0.00747312, 0.15129145, 1.        ],
       [0.45632222, 0.47854952, 0.0504067 , 0.18984049, 1.        ]])

In [217]:
np_matrix = np.random.randint(11,size = (5,5))
np_matrix

array([[ 0,  3,  0,  1,  2],
       [ 8,  9,  1,  8,  9],
       [ 7,  1, 10,  1,  3],
       [ 1,  9,  8,  6,  4],
       [ 4,  1,  3,  7,  3]])

In [218]:
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

array([[2, 1, 1, 0, 2],
       [0, 1, 0, 0, 0],
       [2, 1, 1, 1, 0],
       [0, 1, 1, 2, 0],
       [0, 2, 0, 1, 2]])

In [219]:
row,column = np.where(np_matrix == 2)
[(row[i],column[i]) for i in range(len(row))]

[(0, 0), (0, 4), (2, 0), (3, 3), (4, 1), (4, 4)]

***Ex3***

In [272]:
idx = [1,2,3,4,5]
np_matrix[len(idx)-1,:]

array([4, 5, 6, 4, 9])

In [221]:
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

array([[2, 2, 2, 1, 1],
       [2, 2, 1, 0, 1],
       [1, 1, 0, 0, 2],
       [0, 0, 2, 1, 1],
       [2, 0, 0, 2, 2]])

In [222]:
rng = np.random.RandomState(0)
np_matrix = rng.randint(3,size = (5,5))
np_matrix

array([[0, 1, 0, 1, 1],
       [2, 0, 2, 0, 0],
       [0, 2, 1, 2, 2],
       [0, 1, 1, 1, 1],
       [0, 1, 0, 0, 1]])

In [223]:
np_matrix = np.delete(np_matrix,[1,2],1)
np_matrix

array([[0, 1, 1],
       [2, 0, 0],
       [0, 2, 2],
       [0, 1, 1],
       [0, 0, 1]])

In [224]:
a = np_matrix == 2
a

array([[False, False, False],
       [ True, False, False],
       [False,  True,  True],
       [False, False, False],
       [False, False, False]])

In [225]:
np_matrix[a] = 99
np_matrix

array([[ 0,  1,  1],
       [99,  0,  0],
       [ 0, 99, 99],
       [ 0,  1,  1],
       [ 0,  0,  1]])

In [ ]:
mp_matrix[ np_matrix == 2 ] = 99
mp_matrix

***EX4***

In [241]:
np_matrix = np.random.randint(10,size = (10,5))
np_matrix

array([[1, 8, 4, 0, 4],
       [4, 6, 9, 9, 4],
       [3, 5, 1, 3, 6],
       [1, 6, 1, 1, 8],
       [4, 5, 6, 4, 9],
       [7, 0, 3, 5, 9],
       [3, 0, 8, 9, 6],
       [1, 0, 4, 2, 8],
       [1, 5, 2, 3, 3],
       [8, 5, 3, 5, 8]])

label_vector

In [242]:
vector = np.random.randint(2,size = 10)
vector

array([1, 1, 0, 0, 1, 1, 1, 0, 1, 0])

train_data

In [246]:
np_matrix[np.where(vector == 0)]

array([[3, 5, 1, 3, 6],
       [1, 6, 1, 1, 8],
       [1, 0, 4, 2, 8],
       [8, 5, 3, 5, 8]])

test_data

In [247]:
np_matrix[np.where(vector == 1)]

array([[1, 8, 4, 0, 4],
       [4, 6, 9, 9, 4],
       [4, 5, 6, 4, 9],
       [7, 0, 3, 5, 9],
       [3, 0, 8, 9, 6],
       [1, 5, 2, 3, 3]])